### PR TITLE
i've updated couple of messages

### PR DESCRIPTION
**Pull request by rakeshtinku**
check out !

### CODE REVIEW

**Comment by dmitriytat** [comment]
Can you reformat changes and fix email message "emailId"

**Comment by rakeshtinku** [comment]
Okea i will

**Review by rakeshtinku — COMMENTED** [review]
i've done the change

**Comment by dmitriytat** [comment]
"emailId" isn't right, where did you get it?) 
You write extra spaces in message and padding

**Review by rakeshtinku — COMMENTED** [review]
Is it right now?

**Pull request merged**
